### ISSUE TITLE
setting Color for whole app

### ISSUE THREAD

**Issue by martenbiehl** [armadillu/ofxScreenCurtain#1]
Hi!

Thanks for the addon, working great in a small app I have built.

I had a bit of a problem because after the curtain fell, nothing was shown anymore. Turns out wrapping your draw code a bit helps.

```
ofPushStyle();
curtain.draw();
ofPopStyle();
```

Maybe you want to include that at https://github.com/armadillu/ofxScreenCurtain/blob/b7bb8c5eb1ec3bc340ef76a48da3eb2181322e69/src/ofxScreenCurtain.cpp#L76 to not interfere with other code?

Thanks again!

**Comment by armadillu** [comment]
Thx! push-pop style is quite an expensive call; but I think it makes sense for this object as it will most likely happen only once per frame. Closed by 34efa869cb5b51411cdbbd9acf68987f73e9bbb6

**Comment by martenbiehl** [comment]
that was fast, thanks!

Might be an expensive call, I am quite new to oF. But like you say it might be good in this situation, especially since it is a library. As a beginner I was slightly surprised... :)
